### ISSUE TITLE
dotmap==1.2.5 issue

### ISSUE THREAD

**Issue by 4erpak** [untergeek/zabbix-grab-bag#14]
es_stats_zabbix doesn't work with dotmap 1.2.5:
es_stats_zabbix 
`Traceback (most recent call last):
  File "/usr/bin/es_stats_zabbix", line 7, in <module>
    from es_stats_zabbix.es_stats_zabbix import main
  File "/usr/lib/python2.6/site-packages/es_stats_zabbix/__init__.py", line 2, in <module>
    from .utils import *
  File "/usr/lib/python2.6/site-packages/es_stats_zabbix/utils.py", line 2, in <module>
    from es_stats import *
  File "/usr/lib/python2.6/site-packages/es_stats/__init__.py", line 3, in <module>
    from .utils import *
  File "/usr/lib/python2.6/site-packages/es_stats/utils.py", line 1, in <module>
    from dotmap import DotMap
  File "/usr/lib/python2.6/site-packages/dotmap/__init__.py", line 62
    if k in {'_map','_dynamic', '_ipython_canary_method_should_not_exist_'}:
                   ^
SyntaxError: invalid syntax`

After downgrade dotmap to 1.1.16 it's started working again.

**Comment by untergeek** [comment]
Thanks for the report.  I'll look into what happened.
